version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    ports:
      - '3000:80'
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
