name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, backend]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install deps and build (${{ matrix.service }})
        working-directory: ${{ matrix.service == 'frontend' && 'frontend' || 'backend' }}
        run: |
          npm ci
          npm run build || true
